### ISSUE TITLE
Tutorial01 有些细节问题

### ISSUE THREAD

**Issue by yangruihan** [miloyip/json-tutorial#1]
> 宏的名字必须是唯一的，通常习惯以H_ 作为后缀。由于 leptjson 只有一个头文件，可以简单命名为 LEPTJSON_H__。如果项目有多个文件或目录结构，可以用 项目名称目录文件名称H_ 这种命名方式。

这里 Markdown 语法自动把两个 \_ 变成斜体了，所以显示有点错误~

**Comment by miloyip** [comment]
谢谢，我全部都加 `` 吧。

**Comment by miloyip** [comment]
Fixed in 14966ed92ccd8f2aeff32a9d8302b112c1564b02
