### ISSUE TITLE
第一章 关于函数lept_parse_null()

### ISSUE THREAD

**Issue by zyc737347123** [miloyip/json-tutorial#104]
叶大，在判断后三个字符是否为“ull”时用的是 “||”， 是不是可以改成"&&"，提前结束判断。
还有一个小疑问，在测试"nul"字符时，为什么lept_parse_null()没有发生指针越界？

**Comment by miloyip** [comment]
`||` 的左面为 `false` 也就提前结束判断了。

~~~c
(c->json[0] != 'u' || c->json[1] != 'l' || c->json[2] != 'l')
~~~

等价于

~~~c
!(c->json[0] == 'u' && c->json[1] == 'l' && c->json[2] == 'l')
~~~

[德摩根定律](https://zh.wikipedia.org/zh-cn/%E5%BE%B7%E6%91%A9%E6%A0%B9%E5%AE%9A%E5%BE%8B)

**Comment by zyc737347123** [comment]
明白，谢谢
