### ISSUE TITLE
第7章没有对UTF-8解码

### ISSUE THREAD

**Issue by zyc737347123** [miloyip/json-tutorial#106]
叶大，我想知道怎样从4字节UTF-8解码到Unicode(一个高代理项，一个低代理项)？

**Comment by zyc737347123** [comment]
我之后查阅了一些资料[1]，utf-8的解码是原则上是不应该支持代理对解码的。我问这个问题是出于往返测试无法对\uXXXX进行测试的疑问。
我是这样理解，不用特意的解码成\uXXXX。因为对于我们的解析器，生成器的utf-8输出和原始的\uXXXX,最后编码的结果是一样。不知道我的理解对不对

[1]http://unicodebook.readthedocs.io/issues.html#strict-utf8-decoder

**Comment by miloyip** [comment]
这个库并不需要解码 UTF-8，因为它假设 JSON 和解释后的 DOM 都以 UTF-8 编码。
但在解析时，需要处理 JSON 中的 `\uXXXX`，需要把一个或两个`\uXXXX` 转换成 code point，然后编码成 UTF-8。这个在 https://zhuanlan.zhihu.com/p/22731540 应该解释得颇清楚啊。

**Comment by zyc737347123** [comment]
恩，是我对第四章有些不理解，谢谢叶大的解释
