### ISSUE TITLE
tutorial07 test.c文件    当我增加一行 TEST_ROUNDTRIP("\"Hello\\u20ACWorld\"");

### ISSUE THREAD

**Issue by zput** [miloyip/json-tutorial#121]
程序得到:
d:\github_repository\json-tutorial\tutorial07_answer\test.c:414: expect: "Hello\u20ACWorld" actual: "Hello鈧琖orld"

我的疑问是, 为什么在生成的时候, 不需要判断一个字节是否  >0x7f  了?
通过判断第一个字节是否在下面的那个区间, 就知道了后面还有多少个字节, 然后组成 \uXXXX OR \uXXXXX

码点范围 | 码点位数 | 字节1 | 字节2 | 字节3 | 字节4
-- | -- | -- | -- | -- | --
U+0000 ~ U+007F | 7 | 0xxxxxxx |   |   |  
U+0080 ~ U+07FF | 11 | 110xxxxx | 10xxxxxx |   |  
U+0800 ~ U+FFFF | 16 | 1110xxxx | 10xxxxxx | 10xxxxxx |  
U+10000 ~ U+10FFFF | 21 | 11110xxx | 10xxxxxx | 10xxxxxx | 10xxxxx

**Comment by miloyip** [comment]
因为 JSON 标准中，字符串中少于 0x20 的 codepoint 才必须要转义（escaping），其他值可直接用 UTF-8/16/32来编码。读入时没有转义和有转议的都要支持，输出时可选择只支持一种。这个项目只支持  UTF-8，选择输出时直接输出 UTF-8。

**Comment by zput** [comment]
谢谢老师
