### ISSUE TITLE
第一章对INVALID_VALUE类型错误的处理

### ISSUE THREAD

**Issue by wangzc93** [miloyip/json-tutorial#124]
第一章中对 LEPT_PARSE_INVALID_VALUE 类型的错误，是否少写了一种情况，即合法字符串后面拼接非空白字符串，如："truete"。
目前程序会将这种情况视为 LEPT_PARSE_ROOT_NOT_SINGULAR。
`EXPECT_EQ_INT(LEPT_PARSE_INVALID_VALUE, lept_parse(&v, "truete"));`
输出结果：`expect: 2 actual: 3`

**Comment by miloyip** [comment]
见 #15

**Comment by wangzc93** [comment]
明白了，谢谢老师
