### ISSUE TITLE
tutorial04 里面提到的转义序列

### ISSUE THREAD

**Issue by nangonghuang** [miloyip/json-tutorial#127]
> " U+1D11E 不是 BMP 之内的字符。在 JSON 中可写成转义序列 \uD834\uDD1E"

这里不能直接写4字节的码点吗？比如'\u1D11E' 或者‘\u{1D11E }’之类的。
对于大于0xFFFF的code point ，一定要写成surrogate pair的形式吗？
关于surrogate pair在网上看了一些资料，都说的是 utf-16 对于辅助平面处理，意思是在utf-16编码下， U+1D11E 会被编码成 0xD8340xDD1E  ,长度为4字节。

**Comment by miloyip** [comment]
https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf §9:

> To escape a code point that is not in the Basic Multilingual Plane, the character may be represented as a twelve-character sequence, encoding the UTF-16 surrogate pair corresponding to the code point. So for example, a string containing only the G clef character (U+1D11E) may be represented as "\uD834\uDD1E". However, whether a processor of JSON texts interprets such a surrogate pair as a single code point or as an explicit surrogate pair is a semantic decision that is determined by the specific processor.

如果输出是 UTF-8 或 UTF-16 等编码，可以选择不做转义。但如果转义，就要写成 surrogate pair。
