### ISSUE TITLE
regex无法匹配带小数点的数字

### ISSUE THREAD

**Issue by j178** [miloyip/json-tutorial#13]
在校验JSON number是否有效的练习中, 我使用了`regex.h`中的几个正则表达式函数, 我的正则是这样的:
```
"^-?(0|[1-9]\\d*)(\\.\\d+)?([eE][+-]?\\d+)?$"
```
但是却带小数点的数字(`-0.0`,`1.5`)的测试都失败了, 不知道是什么原因...

**Comment by miloyip** [comment]
C++ 的 `std::regex` 么？

**Comment by miloyip** [comment]
哪个 regex 库？

**Comment by j178** [comment]
@miloyip 抱歉回复晚了. 其实我也不知道是哪个库, 我的环境是cygwin. 查了一下资料, 好像是 *inx 自带的库. 我是通过[这个问题](http://stackoverflow.com/questions/1085083/regular-expressions-in-c-examples) 了解到这个库的.

**Comment by ender233** [comment]
@j178 
我怎么试的时候，这个才是正确的呢
```
^-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\\d+)?$
```

**Comment by j178** [comment]
@ender233 抱歉, 这个正则看着就不对, 而且测试也的确没过. 可以看一下你的 `lept_parse_number()` 的实现吗 ?

**Comment by ender233** [comment]
第二次课我还没做呢  我也试试正则

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Sep 21, 2016 at 3:55 PM +0300, "john jiang" <notifications@github.com<mailto:notifications@github.com>> wrote:


@ender233<https://github.com/ender233> 抱歉, 这个正则看着就不对, 而且测试也的确没过. 可以看一下你的 lept_parse_number() 的实现吗 ?

―
