### ISSUE TITLE
tutorial04 ch=*p++;表达差异带来的报错

### ISSUE THREAD

**Issue by zsyc** [miloyip/json-tutorial#133]
在本章练习中要完成**lept_parse_hex4**函数。
答案中有一句是：
`ch=*p++;`
如果我写成：
`p++;`
`ch=*p;`
就会在测试单元test.c中的line 116 报错……
test.c:116: expect:0 actual:8
test.c:116: expect:4 actual:0
Assertion failed!
……
116行是：
`TEST_STRING("Hello\0World", "\"Hello\\u0000World\"");`

百思不得其解……

**Comment by imba-tjd** [comment]
写成
```c
ch=*p;
p++;
```
就好了
这是前置++和后置++的区别

**Comment by zsyc** [comment]
> 写成
> 
> ```c
> ch=*p;
> p++;
> ```
> 
> 就好了
> 这是前置++和后置++的区别

God，前后置++区别我是知道的，但我之前看网上优先级表，看到++都排在*上面就片面以为++优先级更高，却没发现原来它们是同一优先级的……这里是先取值再自加。
多谢！

**Comment by zsyc** [comment]
> 运算符优先级请参考：https://zh.cppreference.com/w/c/language/operator_precedence
> 后置++优先级确实是最高的，但是p++这个表达式的值是p。
> 如果优先级一样，那就会先和*结合了。

意思是虽然先执行了p++，但是这个++一直到分号；**才会**被执行，于是看似先p++，再解引用（就像我最初的代码一样），但实际上++这个操作因为是后置，所以彻底延后了……
这个后置最高优先级到底在干嘛……还是排到后面去了，够绕的=_=
谢谢

**Comment by imba-tjd** [comment]
p++有两个作用，一是产生它的值，也就是p；第二个是使p=p+1，这个叫做副作用，什么时候生效嘛，那又是另一个话题了，不过分号是会使它生效的。
如果优先级相同，*p++就会是(*p)++了，而实际上是*(p++)，因为++优先级高啊。
这些都是最基本的知识……

**Comment by zsyc** [comment]
> p++有两个作用，一是产生它的值，也就是p；第二个是使p=p+1，这个叫做副作用，什么时候生效嘛，那又是另一个话题了，不过分号是会使它生效的。
> 如果优先级相同，*p++就会是(_p)++了，而实际上是_(p++)，因为++优先级高啊。
> 这些都是最基本的知识……

我之前网上搜到的表跟你给的是不一样的，我之前是按照那个表来理解的
http://c.biancheng.net/cpp/html/462.html

**Comment by chanchancl** [comment]
前置++，在整个表达式求值前就把被操作数加1
后置++，在整个表达式求值后，才改变被操作数
*p++;
++的优先级确实高于*
所以相当于*(p++); 而 p++ 的表达式值是 p 
所以解引用得到的还是*p， 语句执行后，p的值加1

如果有问题，欢迎指正
