### ISSUE TITLE
[Tutorial 01] 解析 `falsee` 等值时返回不合适的返回值

### ISSUE THREAD

**Issue by Ionizing** [miloyip/json-tutorial#154]
如果解析 `falsex` 、 `nullx` 、 `truex` 等末尾多一个非空白字符时，解析函数虽然也可以报错，但是返回的错误是 `LEPT_PARSE_NOT_SINGULAR` ，个人认为正确的返回应当是 `LEPT_PARSE_INVALID_VALUE` 。

**Comment by MrXWTe** [comment]
```c
if ((ret = lept_parse_value(&c, v)) == LEPT_PARSE_OK) {
    lept_parse_whitespace(&c);
    if (*c.json != '\0') {
        ret = LEPT_PARSE_ROOT_NOT_SINGULAR;
    }
}
```
确实，针对 Tutorial 01 的解答部分，这里应该考虑两种情况：
* `false x`这种情况下，我们可以返回LEPT_PARSE_ROOT_NOT_SINGULAR
* `falsex`这种情况下，我们应该返回LEPT_PARSE_INVALID_VALUE
并且在返回解析结果前，是不是应该将type设置为LEPT_NULL，表示我们解析失败了。
```c
if ((ret = lept_parse_value(&c, v)) == LEPT_PARSE_OK) {
    lept_parse_whitespace(&c);
    if (*c.json != '\0') {
        v->type = LEPT_NULL;
        ret = LEPT_PARSE_ROOT_NOT_SINGULAR;
    }
}
```
