### ISSUE TITLE
求问，03中解析字符串时 '\0'是怎么处理的

### ISSUE THREAD

**Issue by nwpuhq** [miloyip/json-tutorial#177]
`static int lept_parse_string(lept_context* c, lept_value* v) {

    size_t head = c->top, len;

    const char* p;

    EXPECT(c, '\"');

    p = c->json;

    for (;;) {

        char ch = *p++;

        switch (ch) {

            case '\"':

                len = c->top - head;

                lept_set_string(v, (const char*)lept_context_pop(c, len), len);

                c->json = p;

                return LEPT_PARSE_OK;

            case '\0':

                c->top = head;

                return LEPT_PARSE_MISS_QUOTATION_MARK;

            default:

                PUTC(c, ch);

        }

    }

}`

> 在 C 语言中，字符串一般表示为空结尾字符串（null-terminated string），即以空字符（`'\0'`）代表字符串的结束。然而，JSON 字符串是允许含有空字符的，例如这个 JSON `"Hello\u0000World"` 就是单个字符串，解析后为11个字符。如果纯粹使用空结尾字符串来表示 JSON 解析后的结果，就没法处理空字符。

上面这两段，是叶哥关于对JSON中'\0'的处理，我感觉在markdown教程中JSON是可以解析'\0'的，但是代码中是直接返回了**LEPT_PARSE_MISS_QUOTATION_MARK**的错误？？？这意味着leptjson不能处理字符串中有'\0'的情况是吗？？例如 "\"abc\0def\""或者 "\"abc0def\""

**Comment by miloyip** [comment]
C 字符串`"\"abc\0def\""` 不是合法的 JSON，Unicode 中的 u+0000 需要转义，`"\"abc\\u0000def\""`才是合法的 JSON。

**Comment by nwpuhq** [comment]
> C 字符串`"\"abc\0def\""` 不是合法的 JSON，Unicode 中的 u+0000 需要转义，`"\"abc\\u0000def\""`才是合法的 JSON。

好的谢谢。'\0' ASCII码是0， '\u0000'ASCII码是1，它们是不同的
