### ISSUE TITLE
cmake configure时的warning是否处理如何处理

### ISSUE THREAD

**Issue by Kong-Aobo** [miloyip/json-tutorial#193]
在使用cmake configure时会提示一个warning 目前来看对项目的学习没有影响  不知道是否需要管它，如果需要管该如何处理？  
warning如下：

> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.  
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

**Comment by imdouyu** [comment]
可以将cmake的minimum_version修改为`cmake_minimum_required (VERSION 2.8.12)`
https://discourse.cmake.org/t/how-to-fix-cmake-minimum-required-deprecation-warning/2487

**Comment by Kong-Aobo** [comment]
OK  多谢多谢
