### ISSUE TITLE
第三章关于EXPECT_EQ_STRING宏的疑问

### ISSUE THREAD

**Issue by relaxcn** [miloyip/json-tutorial#208]
在第三章的`test.c`中的第`24`行
~~~c
#define EXPECT_EQ_STRING(expect, actual, alength) \
    EXPECT_EQ_BASE(sizeof(expect) - 1 == alength && memcmp(expect, actual, alength) == 0, expect, actual, "%s")
~~~
为什么不将此处的`sizeof`更换成`strlen`，这样就不用再减一了。求解答。

还有就是，此处的宏需要传入三个参数，我觉得最后一个长度完全不需要了，直接在宏中使用`strlen`计算即可，为什么这里需要三个参数呢？

**Comment by miloyip** [comment]
> ## 2. 字符串表示
> 在 C 语言中，字符串一般表示为空结尾字符串（null-terminated string），即以空字符（`'\0'`）代表字符串的结束。然而，JSON 字符串是允许含有空字符的，例如这个 JSON `"Hello\u0000World"` 就是单个字符串，解析后为11个字符。如果纯粹使用空结尾字符串来表示 JSON 解析后的结果，就没法处理空字符。
> 因此，我们可以分配内存来储存解析后的字符，以及记录字符的数目（即字符串长度）。由于大部分 C 程序都假设字符串是空结尾字符串，我们还是在最后加上一个空字符，那么不需处理 `\u0000` 这种字符的应用可以简单地把它当作是空结尾字符串。

**Comment by relaxcn** [comment]
明白了明白了😂，是我太愚钝了🤣，想起来strlen是以`\0`表示结尾的。

感谢作者耐心回答👏
