### ISSUE TITLE
数字校验是否有问题

### ISSUE THREAD

**Issue by shibing** [miloyip/json-tutorial#21]
```
 if (*p == '.') {
        p++;
        if (!ISDIGIT(*p)) return LEPT_PARSE_INVALID_VALUE;
        for (p++; ISDIGIT(*p); p++);
    }
    if (*p == 'e' || *p == 'E') {
        p++;
        if (*p == '+' || *p == '-') p++;
        if (!ISDIGIT(*p)) return LEPT_PARSE_INVALID_VALUE;
        for (p++; ISDIGIT(*p); p++);
    }
```

如果`*p`即不是`.`也不是`e`或者`E` 这时候数字也是非法的，比如字符串0m，但是这段代码没有处理这样的情况

**Comment by j178** [comment]
> 因为解析数字时，只会考虑能解析多少合符语法的字符，因此 "0123" 只解析了第一个字符 '0'，转换成 0.0。这个设计的好处是，如果要实现像 RapidJSON 的 kParseStopWhenDoneFlag 这种功能时，"0123" 可能是两个 JSON "0" 和 "123" 串接起来，可以通过两次解析来得出 0.0 和 123.0。我认为解析一个 JSON 类型时，应该尽量解析正确的字符，之后的就交给上级处理。

这是叶老师在另外一个issue的回答. 字符串 `0m` 被解析出 数字`0` 后就返回了, 后续 `lept_parse()`检查右侧的空白符时发现`*c->json != '\0'`, 于是返回 `LEPT_PARSE_ROOT_NOT_SINGULAR`.

**Comment by shibing** [comment]
啊，了解了，谢谢你。
