### ISSUE TITLE
关于tutorial5中内存泄漏的疑问

### ISSUE THREAD

**Issue by relaxcn** [miloyip/json-tutorial#219]
解析数组的解析函数`lept_parse_array`中，假使有错误发生，为什么不在`return`之前直接使用`free(c->stack)`释放栈空间，将`c->size = c->top = 0`呢，而是使用了一个循环弹栈释放。
~~~python
/* Pop and free values on the stack */
    for (i = 0; i < size; i++)
        lept_free((lept_value*)lept_context_pop(c, sizeof(lept_value)));
    return ret;
~~~
还有就是，如果没有错误发生，那么将`c->stack`的内存块复制到`v->u.a.e`中之后，在`c->stack`中的未释放的内存是在函数`lept_parse`中使用`free(c.stack);`释放的吗？
~~~python
int lept_parse(lept_value* v, const char* json) {
//...
    assert(c.top == 0);
    free(c.stack);
    return ret;
}
~~~
感谢回答🤞

**Comment by txtx-cloud** [comment]
如果解析中途出现错误，栈里面还有已经解析了的数据，c->stack指向的是数据之后，free(c.stack)无法释放。
第二个是在lept_parse中释放，只不过不是开始这两句，是最后assert(c.top == 0)；free(c.stack);

**Comment by relaxcn** [comment]
感谢回答，已经明白了😊
