### ISSUE TITLE
不是很理解判断字符tutorial02中连续判断数字的代码 (p++; ISDIGIT(*p); p++); 

### ISSUE THREAD

**Issue by liuxiaomingskm** [miloyip/json-tutorial#236]
Tutorail02Answer中下列代码 [链接](https://github.com/miloyip/json-tutorial/blob/master/tutorial02_answer/leptjson.c#L39)
for (p++; ISDIGIT(*p); p++); 
不是很理解， 第一眼看上去因为p每次循环都自增2次 感觉应该会隔位判断，但是debug了一下 用12345 发现`*p` 显示如下
`2
3
4
5` 
并没有跳过2,4 有点不太理解

**Comment by imdouyu** [comment]
这里的第一个`p++`是跳过[前一行](https://github.com/miloyip/json-tutorial/blob/645d80e849137c85e5a9e54982a9fb50a462e5ea/tutorial02_answer/leptjson.c#L38)已经做过判断的数字，第二个p++，是每次循环指针自增1，也就是循环开始后第一个p++不在参与循环的

**Comment by liuxiaomingskm** [comment]
是的哦 第一个p只是定义 忘了  谢谢指点~
