### ISSUE TITLE
关于tutorial2对含有前导零数字处理的问题

### ISSUE THREAD

**Issue by Asuka-capaccu** [miloyip/json-tutorial#243]
对于含有前导零的数字例如:012，012.12，等等。
我们预期的结果应当是LEPT_PARSE_INVALID_VALUE。但是lept_parse_number()会把它们解析成合法的数字，返回LEPT_PARSE_OK，回到lept_parse中后，执行if判定，由于没有正确调整c.json，lept_parse会返回NOT_SINGULAR。
这样处理不是很规范，最好加上前导零的特判。
类似问题:#176

**Comment by cellphonef** [comment]
> 对于含有前导零的数字例如:012，012.12，等等。 我们预期的结果应当是LEPT_PARSE_INVALID_VALUE。但是lept_parse_number()会把它们解析成合法的数字，返回LEPT_PARSE_OK，回到lept_parse中后，执行if判定，由于没有正确调整c.json，lept_parse会返回NOT_SINGULAR。 这样处理不是很规范，最好加上前导零的特判。 类似问题:#176

我觉得作者的json解析是尽最大可能解析（把能解析的部分都解析了），即把0解析了，但后面的已经无法再解析了，尽最大可能把012，012.12中的0解析了，但后面发现还有多余的字符，此时判断解析失败，因此返回LEPT_PARSE_ROOT_NOT_SINGULAR。我觉得这种做法是合理的。
