### ISSUE TITLE
EXPECT_FALSE()宏有问题！

### ISSUE THREAD

**Issue by fanjinhua** [miloyip/json-tutorial#25]
这样传参的话：EXPECT_FALSE(lept_get_boolean(&v))
lept_get_boolean() 正常情况下返回 LEPT_FALSE（1）
而宏展开则是 (actual) == 0，
应该是 (actual) == 1 才符合测试。

**Comment by fanjinhua** [comment]
EXPECT_FALSE(lept_get_boolean(&v))
lept_get_boolean()正常情况下返回LEPT_FALSE（1）
而宏展开则是(actual) == 0。

**Comment by chanchancl** [comment]
你好，我觉得你可能对lept_get_boolean()返回值有点误解，
lept_get_boolean()返回的应该是，v所代表的布尔值对应的 0或1
而不是 LEPT_FALSE 或者 LEPT_TRUE
具体我是这样实现的，这样EXPECT_FALSE没问题
int lept_get_boolean(const lept_value* v) {
    /* \TODO */
	assert(v->type == LEPT_TRUE || v->type == LEPT_FALSE);
    return v->type == LEPT_TRUE ? 1 : 0;
}

**Comment by fanjinhua** [comment]
这样啊，那我理解错了...

**Comment by j178** [comment]
@chanchancl 可以直接写成 `return v->type == LEPT_TRUE;` 吧 😄 当然, 你这样写清晰一些.
