### ISSUE TITLE
LEPT_PARSE_INVALID_STRING_CHAR

### ISSUE THREAD

**Issue by imbaqian** [miloyip/json-tutorial#26]
麻烦问一下，LEPT_PARSE_INVALID_STRING_ESCAPE 和LEPT_PARSE_INVALID_STRING_CHAR
的区别是什么？

**Comment by j178** [comment]
```
string = quotation-mark *char quotation-mark
char = unescaped /
   escape (
       %x22 /          ; "    quotation mark  U+0022
       %x5C /          ; \    reverse solidus U+005C
       %x2F /          ; /    solidus         U+002F
       %x62 /          ; b    backspace       U+0008
       %x66 /          ; f    form feed       U+000C
       %x6E /          ; n    line feed       U+000A
       %x72 /          ; r    carriage return U+000D
       %x74 /          ; t    tab             U+0009
       %x75 4HEXDIG )  ; uXXXX                U+XXXX
escape = %x5C          ; \
quotation-mark = %x22  ; "
unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
```
根据叶老师文章中的JSON字符串规范, 可以看到JSON的字符串由 __转义字符__ 和 __非转义字符__ 组成.
其中 **合法的转义字符** 只有 `" \ / b f n r t uXXXX` 这9种, 除了这9种之外的转义字符都是`LEPT_PARSE_INVALID_STRING_ESCAPE `. 
而 **合法的非转义字符** 只包括 `%x20-21` `%x23-5B` `%x5D-10FFFF` 这三个`code point` 范围, 除此之外的都是 `LEPT_PARSE_INVALID_STRING_CHAR` .

**Comment by miloyip** [comment]
👍

**Comment by daoxunchen** [comment]
正斜杠是不是不需要转义？
我看TEST_STRING("\"\\/\b\f\n\r\t","\"\\\"\\\\/\\b\\f\\n\\r\\t\"");这条测试中没有对它转义啊，我程序直接把它当非转义来处理的，测试也通过了。。。

**Comment by imbaqian** [comment]
@daoxunchen 需要吧，这个就是   "\/"

**Comment by tautcony** [comment]
唔  `unescaped = %x20-21 / %x23-5B / %x5D-10FFFF`，这个规范里写的是`code point`的值，但是解析过程中每个循环读一个`char`，怎么样都到不了`0x10FFFF`这么大的值吧。

@daoxunchen `"\/"`和 `"/"`都应被正确解析为`/`才行。测试通过不能代表完全正确（只能说明在当前样例下的输出结果是符合预期的），因为一般测试是无法覆盖所有情况的。

**Comment by miloyip** [comment]
用例的确缺少了 `\`，应该要测 '\/`。如 @tautcony 所说，两种情况都要处理。

现时我们还没考虑怎么处理 UTF-8 -> codepoint 的问题，下一单元就会讲到。

**Comment by hitvery** [comment]
@miloyip @daoxunchen 我一开始也好奇为什么正斜杠需要转义，因为C语言里面是没有这个转义**‘\/’**的，如果要通过测试用例，需要加入特殊的判断。好麻烦啊。。。后来查了一下，[http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped](url)里解释了，是为了在HTML的script中嵌入json，因为HTML中，</ 之后不允许有/，除了最后的/>。
