### ISSUE TITLE
Tutorial01_answer中的一个小问题

### ISSUE THREAD

**Issue by ysrcyx** [miloyip/json-tutorial#28]
```C
if (*c.json != '\0')
    ret = LEPT_PARSE_ROOT_NOT_SINGULAR;
```
这里c并不是指针，为什么要加*  而且我去掉*能make通过。
请问这里加*没问题吗？刚开始学，不太懂。

**Comment by miloyip** [comment]
`c.json` 是 `const char*` 的类型，`*c.json` 等同于 `*(c.json)`，也可写作 `c.json[0]`，都是读取当前指针指向的值。

**Comment by ysrcyx** [comment]
感谢回答，我写的是确实是`c.json[0]`。刚才没看清楚。-，-
个人感觉这样比较好理解，写成`*(c.json)`总觉得理解不了，还是对c的字符了解不太够，需要去多学学。

**Comment by chanchancl** [comment]
'.' 运算符的优先级高于 *,
所以 *c.json  就等于  *(c.json)
而， c.json 如 M大大所说，是一个 const char*
