### ISSUE TITLE
小数比较直接使用“==”为何可行？

### ISSUE THREAD

**Issue by hitvery** [miloyip/json-tutorial#29]
叶老师好，在比较double类型的宏实现中
`#define EXPECT_EQ_DOUBLE(expect, actual) EXPECT_EQ_BASE((expect) == (actual), expect, actual, "%.17g")`
一般浮点数比较不能直接像整数一样，还是说在给定的测试用例下可以用此方式?因为expect保存在内存中的值就是会和转换后的actual完全一样的?

**Comment by miloyip** [comment]
这里的要求是完全一样。
通常要检查两个浮点数是否接近，是因为那些值是经过运算而得，浮点运算过程有误差。

**Comment by keithnull** [comment]
然而我这里这样的比较不可行，应该是和平台有关？

```
C:\MyCode\leptjson\test.c:64: expect: 3.1415999999999999 actual: 3.1415999999999999
```
