### ISSUE TITLE
lept_type增加一个LEPT_NONE是不是更好

### ISSUE THREAD

**Issue by actboy168** [miloyip/json-tutorial#31]
现在没有值和‘null’都是用LEPT_NULL

**Comment by miloyip** [comment]
有需要表示「没有值」么？

**Comment by actboy168** [comment]
发生错误之后会被置为LEPT_NULL，还有lept_value初始化和被释放之后

**Comment by miloyip** [comment]
可以这么设计的，但我觉得一般用 null 以足够。
因为操作会返回错误值，已经可以用于检测错误，不需通过 none 这种值来检测。
这种设计比较轻量化一些（例如lept_free() 的 switch 会少一个case）。
当然，加入 none 也是没问题的。

**Comment by actboy168** [comment]
好吧
