### ISSUE TITLE
堆栈的push操作为何需要PUTC宏

### ISSUE THREAD

**Issue by dai-pch** [miloyip/json-tutorial#34]
请问，为什么lept_context_push要设计成返回一个指针，然后配合PUTC宏实现push操作；而不是直接将要push的内容作为参数传入lept_context_push中，在函数里完成操作？

**Comment by miloyip** [comment]
是可以的。
不过因为这段代码源自完成版，这个函数会用于数组和对象的压栈，现时未看到它的这个通用性。

**Comment by dai-pch** [comment]
谢谢
