### ISSUE TITLE
缺少对堆栈top置零操作的测试？

### ISSUE THREAD

**Issue by dai-pch** [miloyip/json-tutorial#35]
LEPT_PARSE_INVALID_STRING_ESCAPE或LEPT_PARSE_INVALID_STRING_CHAR错误之后，若未将top置零，则可能assertion错误，但在测试中未能检测这一点。
是否需要增加这样的测试？

**Comment by miloyip** [comment]
我记得有回复的，如 https://github.com/miloyip/json-tutorial/blob/master/tutorial03_answer/leptjson.c#L117

**Comment by dai-pch** [comment]
是的，我的意思是，测试没覆盖到这一点。之前我忘写这一句，测试仍然通过了。
