### ISSUE TITLE
字符串解析测试用例test_parse_invalid_string_escape()的疑问

### ISSUE THREAD

**Issue by hitvery** [miloyip/json-tutorial#36]
叶老师你好，在解析字符串单元，`static void test_parse_invalid_string_escape()`函数中，认为"\"\\\\v\"" 这样的字符串是LEPT_PARSE_INVALID_STRING_ESCAPE，但是我认为这样转换后是实际字符串是“\v”，有效，因为有两个back slash，可以解释为‘\’，然后之后任意字符没有问题。
如果是"\"\v\""，这样的确是有问题的。
我认为用例中应该去掉一个斜杠。参见：
![string parse flow](http://i.stack.imgur.com/SHLOB.gif)

**Comment by miloyip** [comment]
下面是一个不合法的JSON：
~~~js
"\v"
~~~

这 JSON 转换成 C 字符串（用 C 的转义 `"` -> `\"`, `\` -> `\\`）：
~~~c
const char* json = "\"\\v\"";
~~~

**Comment by hitvery** [comment]
按照您的意思，解析字符串的目的是，从文件中读入字符流，此时这些读入的字符，只是单纯按照字面值转义后的字符。然后我们将其转换为C语言可以识别的有效的转义字符。
其实就类似printf("%d \n\r\t"); 函数的内部实现是吗？printf接受的也是这样转义后的\\n \\r \\t，然后转换为真正的'\n' '\r' '\t'。明白了，谢谢。

**Comment by miloyip** [comment]
前面是正确的，后面不完全正确。`printf("\n\r\t")` 中的 "\n\r\t" 是 C 字符串字面量，实际上是等价于 `{ 10, 13, 9, 0 }`，这是 C 语言的转义，在 C 程序编译时进行解析的，而不是在运行时。

**Comment by hitvery** [comment]
谢谢，原来如此，纠正了一直以来的误区，开心。
