### ISSUE TITLE
关于boolean类型访问函数的疑惑

### ISSUE THREAD

**Issue by Winging** [miloyip/json-tutorial#45]
int lept_get_boolean(const lept_value* v) {
    assert(v != NULL && (v->type == LEPT_TRUE || v->type == LEPT_FALSE));
    return v->type == LEPT_TRUE;
}

void lept_set_boolean(lept_value* v, int b) {
    lept_free(v);
    v->type = b ? LEPT_TRUE : LEPT_FALSE;
}

为什么不直接用LEPT_TRUE, LEPT_FALSE 这两个类型作为返回值呢？

**Comment by j178** [comment]
比如服务器返回的JSON `{"error" : true}`, 使用这个库解析之后, 可以这样使用
```c
if(lept_get_boolean(&v)){
/* */
}
```
如果使用 `LEPT_TRUE` 这些库的自定义类型, 就无法这样了.
解析就是为了把 JSON 中的数据类型转换为 C 语言中数据类型, 库的使用者不需要知道 `LEPT_TRUE` 这些类型, 只需要使用C语言中数据类型就可以.

**Comment by miloyip** [comment]
或者另一个思路是，如果直接用 `LEPT_TRUE`, `LEPT_FALSE`，只需要用 `lept_get_type()` 就可以了。
`lept_get_boolean()` 是为了转换成 C 的布尔值（0 = false, non-zero = true）。

**Comment by Winging** [comment]
嗯，明白了，谢谢。
