### ISSUE TITLE
第二章第三问测试代码有问题

### ISSUE THREAD

**Issue by SmallBookworm** [miloyip/json-tutorial#59]
当把tutorial02/test.c中117行和120行去掉以后，在CLion中运行报错为
`/Users/peng/Documents/json-tutorial-master/tutorial02/test.c:118: expect: 4 actual: 0
/Users/peng/Documents/json-tutorial-master/tutorial02/test.c:118: expect: 0 actual: 3
/Users/peng/Documents/json-tutorial-master/tutorial02/test.c:119: expect: 4 actual: 0
/Users/peng/Documents/json-tutorial-master/tutorial02/test.c:119: expect: 0 actual: 3`
不知道为何会重复运行。

**Comment by j178** [comment]
这不是重复运行了.
我查看 `gcc -E` 预处理后的文件发现, 所有的宏都是展开成一行的. 
`TEST_ERROR` 中用到了两次 `TEST_EQ_INT`, 这两个测试都没有通过, 所以会出现两个错误出现在同一行的现象.

**Comment by SmallBookworm** [comment]
是哦，懂了
