### ISSUE TITLE
关于 lept_member

### ISSUE THREAD

**Issue by chanchancl** [miloyip/json-tutorial#64]
lept_member 的 key 
应不应该支持字符  ':'
比如 
{
"name:1" : "LiHua"
}

**Comment by j178** [comment]
只要是合法的 JSON 字符串都可以作为 object 的 key, 所以包含冒号没有问题.

**Comment by miloyip** [comment]
对的，沿用之前的字符串解析函数（需重构）便可。

**Comment by chanchancl** [comment]
@j178 @miloyip   好的，谢谢
