### ISSUE TITLE
函数static的作用？

### ISSUE THREAD

**Issue by dai-pch** [miloyip/json-tutorial#65]
请问：
为什么项目里的函数大多声明为static的？这样做有什么好处？
以及，一般在什么情况下将函数声明为static的，什么情况下作为普通函数？

**Comment by miloyip** [comment]
static 函数表示该函数只可以在所在的 .c 文件中使用，限制了它的作用域。
非 static 的函数就是所有 .c 文件都可以调用的，只需加上函数声明。
因为非 static 的函数在整个程序中都可使用，名字必须是唯一的，否则会有重复名字的链接错误。
所以，只有外部需要的函数才定义为非 static，内部用的函数都定义为 static。
参考 [file scope](http://en.cppreference.com/w/c/language/scope)。

**Comment by dai-pch** [comment]
谢谢~
