### ISSUE TITLE
在java环境下实现lept-json的问题：\xNN的test case可否直接认为成\u00NN

### ISSUE THREAD

**Issue by Pezhin** [miloyip/json-tutorial#67]
我是用Scala练习写这个tutorial, 但是`\x` escape在Java中是不存在的

Java用的是UTF-16，并不支持`\x`的escape，能否直接把test case修改成\u00NN, 这样的修改有什么隐患吗？

**Comment by miloyip** [comment]
没有问题。这只是语言的字面值表示方式不同。

**Comment by Pezhin** [comment]
多谢~
