### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by KivyGogh** [miloyip/json-tutorial#7]
起始项目的时候遇到：
goudandeMacBook-Pro:mini-JSON goudan$ cmake -DCMAKE_BUILD_TYPE=Debug ..
CMake Error: The source directory "/Users/kivygogh" does not appear to contain CMakeLists.txt.

/Users/kivygogh是我的根目录，第一次接触cmake，有点不知所以，求教作者大神原因？：)

**Comment by luminocean** [comment]
```
$ brew install cmake
$ cd github/json-tutorial/tutorial01
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ make
```
注意示例里面是先创建了`build`目录以后，`cd`到这个`build`目录里面再执行`cmake`的。你执行命令的位置不对。
`cmake`要求指定的目录里面有`CMakeLists.txt`文件。

**Comment by yangruihan** [comment]
> cmake -DCMAKE_BUILD_TYPE=Debug ..

Debug 后面带的是路径，`..`表示上一级目录

**Comment by KivyGogh** [comment]
我确实没进到build里面……但是刚才`cd build`了一下，然后`cmake -DCMAKE_BUILD_TYPE=Debug ..`还是不行，目录里没`CMakeLists.txt`文件。但是我确实很认真的`brew install cmake`了啊 😢

**Comment by miloyip** [comment]
你在哪个目录？键入`pwd` 看看，再 `ls ..` 看看有没有 CMakeLists.txt

**Comment by KivyGogh** [comment]
```
goudandeMacBook-Pro:~ goudan$ cd mini-json
goudandeMacBook-Pro:mini-json goudan$ pwd
/Users/kivygogh/mini-json
goudandeMacBook-Pro:mini-json goudan$ cd build
goudandeMacBook-Pro:build goudan$ pwd
/Users/kivygogh/mini-json/build
goudandeMacBook-Pro:build goudan$ ls ..
build
goudandeMacBook-Pro:build goudan$ cd CMakeLists.txt
-bash: cd: CMakeLists.txt: No such file or directory
goudandeMacBook-Pro:build goudan$ cd ..
goudandeMacBook-Pro:mini-json goudan$ cd CMakeLists.txt
-bash: cd: CMakeLists.txt: No such file or directory
```
...是我没装好么T-T

**Comment by miloyip** [comment]
你好像没有下载或 clone 这个项目的源文件。
简单一点的话，在主面右方找 Clone or download，或直接点 https://github.com/miloyip/json-tutorial/archive/master.zip

**Comment by KivyGogh** [comment]
啊……抱歉🙈谢谢
