### ISSUE TITLE
Tutorial 4 `lept_parse_hex4(const char* p, unsigned* u) `

### ISSUE THREAD

**Issue by jsvoid** [miloyip/json-tutorial#71]
~`lept_parse_hex4(const char* p, unsigned* u)` 中循环条件应该改成 `for (i = 0; i < 4 && p; ++i)`，判断 `p` 不为 `NULL`。
在`p`只剩4个字符的情况下，即使parse的hex是有效的，但是也返回`NULL`，感觉并不是很合适。~
不好意思，当时理解错了

**Comment by rqy1994** [comment]
你能举一个具体的例子吗？对于你的第二句话，有点不太理解。thanks~
