### ISSUE TITLE
第一章 宏中的fprintf第二个参数

### ISSUE THREAD

**Issue by shiyugege** [miloyip/json-tutorial#77]
"%s:%d: expect: " format " actual: " format "\n"

为什么可以这样写啊？双引号不用转义么？忽然想不懂了，求人解惑，谢谢。

**Comment by miloyip** [comment]
format 是一个宏参数，它必须是一个字符串字面量，C 语言可以把字符串字面量串接，如：

~~~c
const char s[] = "Hello"    "World";
~~~
这原来是两个字符串字面量，会在编译期串接为一个字符串字面量 `"HelloWorld"`。

**Comment by shiyugege** [comment]
感谢
