### ISSUE TITLE
在tutorial07中，stringify_string为什么没有对大于0x80的unicode进行处理？

### ISSUE THREAD

**Issue by daoxunchen** [miloyip/json-tutorial#83]
在stringify_string中只对ch<0x20转换为\u0000，对于其他直接PUT进去了

对于那些拥有高低代理项的，为什么没有处理？这里不是很明白

**Comment by miloyip** [comment]
在 `Value` 中的字符串是以 UTF-8 编码的，所以可以直接输出成 UTF-8 的 JSON。
JSON 规定只有 `ch < 0x20` 的必须转换成 `U+00XX`。
其他字符，可以用编码本身的方式写入，**或** 是 `U+XXXX`。
在 RapidJSON 中，特别做了一个 ASCII 编码格式，必然把 `ch >= 0x80` 的字符都以 `U+XXXX` 形式输出。

但对于解析器，必须能解析两种形式。

**Comment by daoxunchen** [comment]
Thanks
