### ISSUE TITLE
关于tutorial01下的null单元测试代码

### ISSUE THREAD

**Issue by MeteorGX** [miloyip/json-tutorial#87]
叶老师您好，这段测试下的是v.type = LEPT_NULL吗?还是本身就是LEPT_TRUE
____
> static void test_parse_null() {
    lept_value v;
    v.type = LEPT_TRUE;
    EXPECT_EQ_INT(LEPT_PARSE_OK, lept_parse(&v, "null"));
    EXPECT_EQ_INT(LEPT_NULL, lept_get_type(&v));
}

**Comment by hitvery** [comment]
你好，你可能没有更新最新的代码，新版的tutorial01的代码和你的不同，可以在github中看到：
```
static void test_parse_null() {
    lept_value v;
    v.type = LEPT_FALSE;
    EXPECT_EQ_INT(LEPT_PARSE_OK, lept_parse(&v, "null"));
    EXPECT_EQ_INT(LEPT_NULL, lept_get_type(&v));
}
```
在一个lept_value 变量初始化时，都会给type赋值为false。在parse字符串后type会有相应的变化。

**Comment by MeteorGX** [comment]
好的，十分感谢
