### ISSUE TITLE
关于断言的疑问

### ISSUE THREAD

**Issue by gatsbydhn** [miloyip/json-tutorial#99]
第一章的leptjson.c文件中的第19行：
EXPECT(c, 'n');
#define EXPECT(c, ch)       do { assert(*c->json == (ch)); c->json++; } while(0)
那么在release 版中是否会和debug版行为一致？

**Comment by valdsJohn** [comment]
肯定一致啊，c->json++又不在assert里面

**Comment by j178** [comment]
我觉得`assert`的作用是为了发现程序的Bug，而不是发现运行时的错误。
比如说这里的`assert(*c->json == (ch))`在正常运行时肯定不会报错，因为传给这个函数时就已经保证了`*c->json==(ch)`，但是如果报错了，就说明程序在传给函数之前有哪里写错了。

**Comment by gatsbydhn** [comment]
明白了，调用lept_parse_null时，保证*c->json == 'n'是调用者的责任。
